<a href="https://colab.research.google.com/github/Miokasa/MLC/blob/master/week3_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

The company has provided you with
synthetic data representing delivery times (in minutes) and package weights (in kilograms) for
100 deliveries.

Tasks:
Task 1: Data Preparation
1. Generate two 1D arrays:
- delivery_times: 100 random integers between 30 and 120 (inclusive).
- package_weights: 100 random floats between 0.5 and 10.0 (inclusive, rounded to two
decimal places).
(Use np.random.randint and np.random.uniform for this task. )
2. Combine these arrays into a single 2D array called data where:
- The first column represents delivery times.
- The second column represents package weights.

In [2]:
delivery_times=np.random.randint(low=30,high=121,size=100) #high is not included
package_weights=np.round(np.random.uniform(low=0.5,high=10.0,size=100),2)  #high is included
data=np.column_stack((delivery_times,package_weights)) #np.column_stack((a,b)) is better than np.concatenate((a,b),axis=0)
print(data.shape)
data[:5]

(100, 2)


array([[ 53.  ,   1.39],
       [114.  ,   1.44],
       [ 58.  ,   4.16],
       [107.  ,   4.29],
       [ 84.  ,   4.93]])

Task 2: Basic Statistics
1. Calculate the following statistics for delivery times:
- Mean, median, standard deviation, and maximum value.
2. Calculate the following statistics for package weights:
- Mean, minimum value, and range (max - min).
3. Identify how many deliveries took more than 90 minutes.

In [6]:
data_mean=np.mean(data[:,0])
data_median=np.median(data[:,0])
data_std=np.std(data[:,0])
data_max=np.max(data[:,0])
data_min=np.min(data[:,0])
print(f'Statistics for delivery times: Mean:{data_mean}, Median:{data_median}, Standard Deviation:{data_std}, Maximum value:{data_max}')

Statistics for delivery times: Mean:77.4, Median:74.0, Standard Deviation:23.30364778312614, Maximum value:118.0


In [7]:
data_mean2=np.mean(data[:,1])
data_max2=np.max(data[:,1])
data_min2=np.min(data[:,1])
data_range2=np.subtract(data_max2,data_min2)
print(f'Statistics for package weights: Mean:{data_mean2}, Manimum value:{data_min2}, Rnage:{data_range2}')

Statistics for package weights: Mean:5.402700000000002, Manimum value:0.55, Rnage:9.29


In [9]:
deliveries_more_than_90 = data[data[:,0]>90]
numbers=deliveries_more_than_90.shape[0]
print(f'There are {numbers} deliveries took more than 90 minutes. ')

There are 37 deliveries took more than 90 minutes. 


Task 3: Filtering and Logical Indexing
1. Create a new array heavy_packages containing only rows where the package weight
exceeds 5 kg.
2. From heavy_packages, identify how many deliveries took less than or equal to 60 minutes.

In [11]:
heavy_packages=np.array(data[data[:,1]>5])
deliveries_less_or_equal_60 = heavy_packages[heavy_packages[:,0]<=60]
nums = deliveries_less_or_equal_60.shape[0]
print(f'There are {nums} deliveries took less than or equal to 60 minutes.')

There are 16 deliveries took less than or equal to 60 minutes.


Task 4: Data Transformation
1. Normalize the delivery times in data (scale values between 0 and 1). Add the normalized
values as a third column in the array.
2. Sort the rows of data by package weight in descending order.

In [12]:
times_normalized = (data[:,0] - data_min) / (data_max - data_min) # using the formula
data=np.column_stack((data,times_normalized))
data[:5]

array([[ 53.        ,   1.39      ,   0.22619048],
       [114.        ,   1.44      ,   0.95238095],
       [ 58.        ,   4.16      ,   0.28571429],
       [107.        ,   4.29      ,   0.86904762],
       [ 84.        ,   4.93      ,   0.5952381 ]])

In [13]:
new=data[np.argsort(data[:,1])[::-1]] #argsort can give the sorted index, and [::-1]can reverse the index by descenting order.
new[:5]

array([[ 68.        ,   9.84      ,   0.4047619 ],
       [104.        ,   9.83      ,   0.83333333],
       [ 70.        ,   9.74      ,   0.42857143],
       [ 84.        ,   9.67      ,   0.5952381 ],
       [ 74.        ,   9.6       ,   0.47619048]])

Task 5: Advanced Analysis
1. Group the data into three categories based on delivery times:
- Category A: delivery time <= 60
- Category B: 60 < delivery time <= 90
- Category C: delivery time > 90
Create a new array categories where each row contains the category label (A, B, or C)
corresponding to each delivery.
2. Calculate the average package weight for each category.

In [21]:
data=np.column_stack((delivery_times,package_weights)) # Stack delivery times and package weights into a 2D array
categories = [] #store labels based on delivery times in order
for time in data[:, 0]:
    if time <= 60:
        categories.append('A')
    elif 60 < time <= 90:
        categories.append('B')
    else:
        categories.append('C')

categories_array=np.array(categories)  # Convert the list of categories into a numpy array
data=np.column_stack((data,categories_array))  # Add the categories as a third column
print(data.shape)
print(data[:5])

(100, 3)
[['107.0' '1.01' 'C']
 ['85.0' '0.65' 'B']
 ['48.0' '3.18' 'A']
 ['52.0' '9.59' 'A']
 ['99.0' '5.83' 'C']]


In [22]:
mean_A=np.mean(package_weights[np.array(categories) == 'A'])
mean_B=np.mean(package_weights[np.array(categories) == 'B'])
mean_C=np.mean(package_weights[np.array(categories) == 'C'])

print(f"Category A average weight: {mean_A:.2f}")
print(f"Category B average weight: {mean_B:.2f}")
print(f"Category C average weight: {mean_C:.2f}")

Category A average weight: 5.78
Category B average weight: 4.92
Category C average weight: 5.75


Hints:
- Use slicing (:) and logical conditions (> , < , etc.) for filtering data.
- For normalization, use the formula: x_normalized = (x - x_min) / (x_max - x_min).
- To sort rows by a specific column, use np.argsort.