<a href="https://colab.research.google.com/github/Miokasa/MLC/blob/master/week3mlc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
!pip install numpy
!conda install numpy  #从外界环境下载shell command 要加！，不是本地的cloud或者jupyter带的

In [ ]:
list1=[1,2,3,4,5]
array1=np.array(list1)
array1

array([1, 2, 3, 4, 5])

In [ ]:
t=(1,2,3,4,5)
array2=np.array(t)
array2

array([1, 2, 3, 4, 5])

In [ ]:
array3=np.arange(10)
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array4=np.arange(0,10,2)
array4

array([0, 2, 4, 6, 8])

In [ ]:
type(array2)

(5,)

In [ ]:
array2.shape

(5,)

In [ ]:
array_2d=np.array([[1,2,3],[4,5,6]])
array_2d.shape

(2, 3)

In [ ]:
zero_array=np.zeros((3,4))
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
ones_array=np.ones((3,6))
ones_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
lines=np.linspace(0,1,8)
lines

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [ ]:
full_array=np.full((2,3),8)
full_array

array([[8, 8, 8],
       [8, 8, 8]])

In [ ]:
print(np.eye(3))
np.eye(4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
array1=np.array([1,2,3,4,5])
array2=np.array([2,3,4,5,6])
sum_array=np.add(array1,array2)
subtract=np.subtract(array1,array2)
multiply=np.multiply(array1,array2)
divide=np.divide(array1,array2)

array([ 3,  5,  7,  9, 11])

In [10]:
#broadcasting
a=np.array([[1,2,],[4,5,]]) #(2,2)
b=np.array([1,2,3]) #(1,3)

In [4]:
print(a+b)
np.add(a,b)

[[2 4 6]
 [5 7 9]]


array([[2, 4, 6],
       [5, 7, 9]])

In [11]:
c = np.array([10, 20])
c.shape #（1,2）

(2,)

In [12]:
np.add(c,a)

array([[11, 22],
       [14, 25]])

In [13]:
A=np.array([1,2,3])
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [14]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [15]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [16]:
np.sum(A)

6

In [39]:
D=np.array([1,2,3,4,5])
print(D[4]==D[-1])
sliced_D=D[2:4]
print(sliced_D)
print(D[-4:-2])
print(D>3)
print(D[D>3])

True
[3 4]
[2 3]
[False False False  True  True]
[4 5]


In [29]:
E=np.array([[1,2,3],[4,5,6],[7,8,9]])
E[1,2]
E[0,1]=99
E
sliced_E=E[1:3,:1]
sliced_E

array([[4],
       [7]])

In [36]:
step_lice=E[::2]
print(E)
step_lice

[[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]]


array([[ 1, 99,  3],
       [ 7,  8,  9]])

In [60]:
D=np.array([1,2,3,4,5])
print(D[[0,1,-1]]) #fancy_index
D[0:2]=[99,66]
print(D)
print('---------------------------')
E=np.array([[1,2,3],[5,6,7],[3,6,9]])
fancy_index2d=E[[1,2],[0,2]]
print(fancy_index2d)
fancy_index2d=[44,55]
print(fancy_index2d)
E
#fancy_index会把截取出来的数据新创建一个列表，再该表新列表的值，不会影响旧列表的值。并且可以无序获取数据，随便用index截取想要的值
#普通的slice 必须是有序的，比如[start,end(exclude),step]，并且slice出来的值修改后会影响原列表的数据

[1 2 5]
[99 66  3  4  5]
---------------------------
[5 9]
[44, 55]


array([[1, 2, 3],
       [5, 6, 7],
       [3, 6, 9]])

In [65]:
arrays=np.arange(1,13)
new = arrays.reshape((2,6))
print(new)
new.flatten() #这里会创新新数组，而不是copy

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [90]:
#concatenated
array1=np.array([[1,2],[3,4]])
array2=np.array([[5,6],[7,8]])
print(array1)
print(array2)
print('---------------------------')
concatenated_array=np.concatenate((array1,array2),axis=0)
print(concatenated_array)
print(concatenated_array.shape)
print('---------------------------')
concatenated_array=np.concatenate((array1,array2),axis=1)
print(concatenated_array)
print(concatenated_array.shape)
#axis=0: Adds rows 横着,增加行数
#axis=1: Adds columns 竖着切，增加列数
# concatenated增加，split减少

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
---------------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
---------------------------
[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [93]:
#split
array = np.arange(12) #np.arange(1,13)
reshaped_array=array.reshape((3,4))
print(reshaped_array)
split_array=np.split(array,3)
print(split_array)
print('----------------------------')
split_reshaped_array=np.split(reshaped_array,3,axis=0)
print(split_reshaped_array)
print('----------------------------')
split_reshaped_array=np.split(reshaped_array,2,axis=1)
print(split_reshaped_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
----------------------------
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
----------------------------
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [94]:
np.mean(array)
np.median(array)
np.var(array)
np.std(array)
np.max(array)
np.min(array)
np.percentile(array,85)

9.35

In [95]:
vector_a=np.array([1,2,3])
vector_b=np.array([4,5,6])
dot_product=np.dot(vector_a,vector_b)
print(dot_product)

32


In [96]:
matrix_a=np.array([[1,2],[3,4]])
matrix_b=np.array([[5,6],[7,8]])
product=np.matmul(matrix_a,matrix_b)
print(product)

[[19 22]
 [43 50]]


In [ ]:
#structered array in numpy vs disctionary in python

In [103]:
structured_array=np.array([(1,'Lucy',46),(2,'Charlie',25),(3,'Jack',16)],dtype=[('id','i4'),('name','U10'),('age','i4')])
structured_array

array([(1, 'Lucy', 46), (2, 'Charlie', 25), (3, 'Jack', 16)],
      dtype=[('id', '<i4'), ('name', '<U10'), ('age', '<i4')])

In [104]:
print(structured_array['name'])
print(structured_array['age'])
print(structured_array['id'])

['Lucy' 'Charlie' 'Jack']
[46 25 16]
[1 2 3]


In [109]:
structured_array['age']=[23,18,93]
sorted_array=np.sort(structured_array,order='age')
print(sorted_array)

[(2, 'Charlie', 18) (1, 'Lucy', 23) (3, 'Jack', 93)]


In [111]:
filted_array=structured_array[structured_array['age']>20]
print(filted_array)

[(1, 'Lucy', 23) (3, 'Jack', 93)]


In [119]:
data=[{'id':1,'name':'Alice','age':23},
   {'id':2,'name':'jack','age':45}]
# structured_wrong=np.array(data,dtype=[('id','i4'),('name','U10'),('age','i4')])
# structured_wrong
#传入的期望是可以直接转换成格式的数据，而不是列表。因此可以将数据都提取出来
list_id=[]
for i in data:
  list_id.append(i['id'])

list_id=[i['id'] for i in data]
list_name=[i['name'] for i in data]
list_age=[i['age'] for i in data]
structured_data=np.array(list(zip(list_id,list_name,list_age)),dtype=[('id','i4'),('name','U10'),('age','i4')])
structured_data
#dtype和前面的数据格式和名称要对应，不然数据格式对应不了，比如u10,i4


array([(1, 'Alice', 23), (2, 'jack', 45)],
      dtype=[('id', '<i4'), ('name', '<U10'), ('age', '<i4')])